[CI] Work around H100 FabricManager failure causing multicast failure (#177472)
Typical signature:
```
torch.distributed.DistBackendError: NCCL error in: /var/lib/jenkins/workspace/torch/csrc/distributed/c10d/NCCLUtils.cpp:93, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.29.3
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Failed to bind NVLink SHARP (NVLS) Multicast memory of size 2097152 : CUDA error 401 'the operation cannot be performed in the present state'.
This is usually caused by a system or configuration error in the Fabric Manager or NVSwitches.
Disable NVLS (NCCL_NVLS_ENABLE=0) if you wish to avoid this error in the future.
```

This PR disables NCCL from using NVLink SHARP by setting  `NCCL_NVLS_ENABLE=0` as suggested.
Note that this is a short-term workaround. We need to restart or fix the machine.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/177472
Approved by: https://github.com/Skylion007