[CuTe][TEST] Fix `test_cutedsl_op_overrides` (#177107)
Not sure this is due to an incorrect check or if the mocks were incomplete (this PR assumes the latter)
Otherwise seems to fail with
```
  File "/usr/lib/python3.12/unittest/mock.py", line 658, in __getattr__
    raise AttributeError("Mock object has no attribute %r" % name)
AttributeError: Mock object has no attribute 'shape'
```
authored with claude code

failing lines were introduced in https://github.com/pytorch/pytorch/commit/6e1dce470745cb6dc6bb1027eba96c31b7adac28

Pull Request resolved: https://github.com/pytorch/pytorch/pull/177107
Approved by: https://github.com/jansel