[2/N] C++20 template method instantiation adjustements (#175612)
Similar to https://github.com/pytorch/pytorch/pull/168132
Non-compliant instantiation were probably introduced by https://github.com/pytorch/pytorch/pull/172685

Fixes a very verbose Windows compilation error that includes 200 `ForeachReduceOp.cu(470): error: type name is not allowed` and 200 `ForeachReduceOp.cu(470): error: expected an expression`

Pull Request resolved: https://github.com/pytorch/pytorch/pull/175612
Approved by: https://github.com/Skylion007